version: '2'
services:
  node1:
    image: blockchain_demo:latest
    restart: always
    depends_on:
      - nats
    ports:
      - "3001:3000"
    networks:
      - blockchain_demo
    environment:
      - NATS_URL=nats://nats:4222
      - JOB_NAME=job1
      - WORKER_NAME=client1

  node2:
    image: blockchain_demo:latest
    restart: always
    depends_on:
      - nats
    networks:
      - blockchain_demo
    ports:
      - "3002:3000"

    environment:
      - NATS_URL=nats://nats:4222
      - JOB_NAME=job2
      - WORKER_NAME=client2

  nats:
    image: nats-streaming
    restart: always
    command: -DV -cid blockchaindemo --store FILE --dir /data
    volumes:
      - natsdata:/data
    networks:
      - blockchain_demo

volumes:
  natsdata: {}

networks:
  blockchain_demo:
    driver: bridge


